[build]
rustflags = ["--cfg", "tokio_unstable"]
target-dir = "target"

[alias]
server = "run --package crime_map_server --release"
"server:debug" = "run --package crime_map_server"
ingest = "run --package crime_map_ingest --release --"
"ingest:debug" = "run --package crime_map_ingest --"
generate = "run --package crime_map_generate --release --"
"generate:debug" = "run --package crime_map_generate --"
discover = "run --package crime_map_discover --release --"
"discover:debug" = "run --package crime_map_discover --"
conversations = "run --package crime_map_conversations --release --"
"conversations:debug" = "run --package crime_map_conversations --"
