id = "denver_pd"
name = "Denver Police Department"
city = "Denver"
state = "CO"
output_filename = "denver_crimes.json"

[license]
license_type = "open_data"
attribution_required = true
attribution_text = "City and County of Denver"
allows_redistribution = true
restricted = false

[fetcher]
type = "arcgis"
query_urls = [
  "https://services1.arcgis.com/zdB7qR0BtYrg0Xpl/ArcGIS/rest/services/ODC_CRIME_OFFENSES_P/FeatureServer/324/query",
]
page_size = 2000
date_column = "FIRST_OCCURRENCE_DATE"

[fields]
incident_id = ["INCIDENT_ID"]
crime_type = ["OFFENSE_TYPE_ID"]
block_address = "INCIDENT_ADDRESS"
location_type = "NEIGHBORHOOD_ID"

[fields.occurred_at]
type = "epoch_ms"
field = "FIRST_OCCURRENCE_DATE"

[fields.lat]
field = "GEO_LAT"
type = "f64"

[fields.lng]
field = "GEO_LON"
type = "f64"

[fields.description]
type = "single"
field = "OFFENSE_TYPE_ID"

[fields.arrest]
type = "none"
