id = "las_vegas_pd"
name = "Las Vegas Metropolitan Police Department"
city = "Las Vegas"
state = "NV"
output_filename = "las_vegas_crimes.json"

[fetcher]
type = "arcgis"
# LVMPD publishes NIBRS data split by crime-against category.
query_urls = [
  "https://services.arcgis.com/jjSk6t82vIntwDbs/arcgis/rest/services/LVMPD_Reported_NIBRS_Crimes_Against_Property/FeatureServer/0/query",
  "https://services.arcgis.com/jjSk6t82vIntwDbs/arcgis/rest/services/LVMPD_Reported_NIBRS_Crimes_Society/FeatureServer/0/query",
]
page_size = 2000
date_column = "ReportedOn"

[fields]
incident_id = ["Event_Number"]
crime_type = ["OffenseCategory", "Offense"]
block_address = "Location"
location_type = "LocationType"

[fields.occurred_at]
type = "epoch_ms"
field = "ReportedOn"

[fields.lat]
field = "Latitude"
type = "f64"

[fields.lng]
field = "Longitude"
type = "f64"

[fields.description]
type = "combine"
fields = ["OffenseCategory", "Offense"]
separator = ": "

[fields.arrest]
type = "none"
