[package]
authors = { workspace = true }
description = "Generic web scraping framework for crime data"
edition = { workspace = true }
license = { workspace = true }
name = "crime_map_scraper"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
chrono = { workspace = true }
csv = { workspace = true }
flate2 = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[features]
default = []
fail-on-warnings = []
